[I 220502 08:28:41 server:155] Serving on http://127.0.0.1:35729
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/livereload/management/commands/livereload.py", line 72, in handle
    liveport=options['port'],
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/livereload/server.py", line 157, in serve
    self.application(host, liveport=liveport)
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/livereload/server.py", line 145, in application
    live.listen(liveport, address=host)
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/tigerit/MyGithub/MyGithub/Django-Simple-Rest-API/v3/lib/python3.6/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
